"""
Django settings for bootie project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

GIT_ROOT = os.path.abspath(__file__).rsplit(os.path.sep, 3)[0]
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FILE_DIR = os.path.abspath(os.path.dirname(__file__))
PROJECT_DIR = os.path.dirname(__file__) 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'f*p2pbwnr&e5@xc$_^!&-ty_s*!lvxlm67n#yomnbmq6z@cco#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ADMINS = (
    ('Tom Meland Pedersen', 'tompersen@gmail.com')
)
MANAGERS = ADMINS

ALLOWED_HOSTS = [
    '127.0.0.1',
    'www.ntnuipadling.no',
    'ntnuipadling.no',
]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Secondary apps
    'imagekit',
    'static_precompiler',
    'captcha',
    #Bootie apps
    'posts',
    'index',
    'weatherforecast',
    'info',
    'paddleusers',
    'events',
    'galleries',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'bootie.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'bootie/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bootie.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bootiedb',
        'USER': 'bootie',
        'PASSWORD': 'beer',
        'HOST': 'localhost',
        'PORT': '',

    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Oslo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_DIR, 'public', 'static')
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(PROJECT_DIR, 'static'),
)

#######################
#    Uploded media    #
#######################

#Media files, images, videos etc.
MEDIA_ROOT = os.path.join(GIT_ROOT, 'public', 'media')
MEDIA_URL = '/media/'



#######################
#     Login info      #
#######################

LOGIN_URL = 'bootie_login'
LOGOUT_URL = 'bootie_logout'
LOGIN_REDIRECT_URL = '/'



#######################
#       Captcha       #
#######################

#######################
#   Easy thumbnails   #
#######################

THUMBNAIL_BASEDIR = 'thumbs'
THUMBNAIL_DEBUG = False